name: Deploy React Demo to Cloudflare Workers

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            core:
              - 'apps/core-demo/**'
            react:
              - 'apps/react-demo/**'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build --filter=core-demo --filter=react-demo --filter=@arrow-navigation/react --filter=@arrow-navigation/core

      - name: Deploy Core Demo
        if: steps.filter.outputs.core == 'true'
        working-directory: ./apps/core-demo
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy React Demo
        if: steps.filter.outputs.react == 'true'
        working-directory: ./apps/react-demo
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

